name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      id: checkout-code
      uses: actions/checkout@v3

    - name: Prepare sources for building
      run: python .github/workflows/code-processing.py
      
    - name: Init .gitmodules
      uses: snickerbockers/submodules-init@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload a usually needed build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: _usually needed artifacts
        path: |
          bin/Release-x64/CLibrary.dll
          bin/Release-x64/injector.exe

    - name: Upload a full build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: full artifacts
        path: bin/Release-x64/
